Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Internal Server Error: /moneymanager/api/login/
Traceback (most recent call last):
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: auth_user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework_simplejwt/views.py", line 43, in post
    serializer.is_valid(raise_exception=True)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework_simplejwt/serializers.py", line 68, in validate
    data = super().validate(attrs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework_simplejwt/serializers.py", line 49, in validate
    self.user = authenticate(**authenticate_kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 77, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/contrib/auth/backends.py", line 46, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 46, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 646, in get
    num = len(clone)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: auth_user
Internal Server Error: /moneymanager/api/login/
Traceback (most recent call last):
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: auth_user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework_simplejwt/views.py", line 43, in post
    serializer.is_valid(raise_exception=True)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework_simplejwt/serializers.py", line 68, in validate
    data = super().validate(attrs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework_simplejwt/serializers.py", line 49, in validate
    self.user = authenticate(**authenticate_kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 77, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/contrib/auth/backends.py", line 46, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 46, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 646, in get
    num = len(clone)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: auth_user
Not Found: /moneymanager/static/rest_framework/css/bootstrap.min.css
Not Found: /moneymanager/static/rest_framework/js/csrf.js
Not Found: /moneymanager/static/rest_framework/js/bootstrap.min.js
Not Found: /moneymanager/static/rest_framework/js/prettify-min.js
Not Found: /moneymanager/static/rest_framework/js/default.js
Not Found: /moneymanager/static/rest_framework/css/bootstrap-tweaks.css
Not Found: /moneymanager/static/rest_framework/js/jquery-3.5.1.min.js
Not Found: /moneymanager/static/rest_framework/css/default.css
Not Found: /moneymanager/static/rest_framework/css/prettify.css
Not Found: /moneymanager/static/rest_framework/js/ajax-form.js
Unauthorized: /moneymanager/api/transfer/
Not Found: /moneymanager/static/rest_framework/css/prettify.css
Not Found: /moneymanager/static/rest_framework/css/bootstrap.min.css
Not Found: /moneymanager/static/rest_framework/css/default.css
Not Found: /moneymanager/static/rest_framework/js/jquery-3.5.1.min.js
Not Found: /moneymanager/static/rest_framework/css/bootstrap-tweaks.css
Not Found: /moneymanager/static/rest_framework/js/default.js
Not Found: /moneymanager/static/rest_framework/js/ajax-form.js
Not Found: /moneymanager/static/rest_framework/js/csrf.js
Not Found: /moneymanager/static/rest_framework/js/bootstrap.min.js
Not Found: /moneymanager/static/rest_framework/js/prettify-min.js
[UID:2035][4046564] Child process with pid: 4046615 was killed by signal: 15, core dump: 0
[UID:2035][692434] Child process with pid: 692646 was killed by signal: 15, core dump: 0
Traceback (most recent call last):
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 15, in <module>
    import MySQLdb as Database
ModuleNotFoundError: No module named 'MySQLdb'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nappmyid/python/moneymanager/passenger_wsgi.py", line 7, in <module>
    from moneymanager.wsgi import application
  File "/home/nappmyid/python/moneymanager/moneymanager/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/contrib/auth/models.py", line 3, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 49, in <module>
    class AbstractBaseUser(models.Model):
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/models/base.py", line 141, in __new__
    new_class.add_to_class("_meta", Options(meta, app_label))
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/models/base.py", line 369, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/models/options.py", line 231, in contribute_to_class
    self.db_table, connection.ops.max_name_length()
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/utils.py", line 193, in create_connection
    backend = load_backend(db["ENGINE"])
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/utils.py", line 113, in load_backend
    return import_module("%s.base" % backend_name)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 17, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
Did you install mysqlclient?
Traceback (most recent call last):
  File "/home/nappmyid/python/moneymanager/passenger_wsgi.py", line 7, in <module>
    from moneymanager.wsgi import application
  File "/home/nappmyid/python/moneymanager/moneymanager/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
[UID:2035][3478720] Child process with pid: 3479387 was killed by signal: 15, core dump: 0
[UID:2035][812797] Child process with pid: 827970 was killed by signal: 15, core dump: 0
[UID:2035][396482] Child process with pid: 397561 was killed by signal: 15, core dump: 0
[ERROR] [UID:2035][2214819] wsgiAppHandler pApp->start_response() return NULL.
Traceback (most recent call last):
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 313, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nappmyid/python/moneymanager/moneymanager/urls.py", line 24, in <module>
    path('api/',include('api.urls')),
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nappmyid/python/moneymanager/api/urls.py", line 5, in <module>
    from .views import RegisterView
  File "/home/nappmyid/python/moneymanager/api/views.py", line 22, in <module>
    import requests as req_lib
ModuleNotFoundError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 58, in inner
    response = response_for_exception(request, exc)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 182, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 66, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 396, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 381, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 99, in get_caller
    resolver_match = resolve(request.path)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nappmyid/python/moneymanager/moneymanager/urls.py", line 24, in <module>
    path('api/',include('api.urls')),
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nappmyid/python/moneymanager/api/urls.py", line 5, in <module>
    from .views import RegisterView
  File "/home/nappmyid/python/moneymanager/api/views.py", line 22, in <module>
    import requests as req_lib
ModuleNotFoundError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 58, in inner
    response = response_for_exception(request, exc)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 182, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 66, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 396, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 381, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 99, in get_caller
    resolver_match = resolve(request.path)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nappmyid/python/moneymanager/moneymanager/urls.py", line 24, in <module>
    path('api/',include('api.urls')),
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nappmyid/python/moneymanager/api/urls.py", line 5, in <module>
    from .views import RegisterView
  File "/home/nappmyid/python/moneymanager/api/views.py", line 22, in <module>
    import requests as req_lib
ModuleNotFoundError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 58, in inner
    response = response_for_exception(request, exc)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 182, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 66, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 396, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 381, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 99, in get_caller
    resolver_match = resolve(request.path)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nappmyid/python/moneymanager/moneymanager/urls.py", line 24, in <module>
    path('api/',include('api.urls')),
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nappmyid/python/moneymanager/api/urls.py", line 5, in <module>
    from .views import RegisterView
  File "/home/nappmyid/python/moneymanager/api/views.py", line 22, in <module>
    import requests as req_lib
ModuleNotFoundError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 58, in inner
    response = response_for_exception(request, exc)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 182, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 66, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 396, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 381, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 99, in get_caller
    resolver_match = resolve(request.path)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nappmyid/python/moneymanager/moneymanager/urls.py", line 24, in <module>
    path('api/',include('api.urls')),
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nappmyid/python/moneymanager/api/urls.py", line 5, in <module>
    from .views import RegisterView
  File "/home/nappmyid/python/moneymanager/api/views.py", line 22, in <module>
    import requests as req_lib
ModuleNotFoundError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 58, in inner
    response = response_for_exception(request, exc)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 182, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 66, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 396, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 381, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 99, in get_caller
    resolver_match = resolve(request.path)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nappmyid/python/moneymanager/moneymanager/urls.py", line 24, in <module>
    path('api/',include('api.urls')),
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nappmyid/python/moneymanager/api/urls.py", line 5, in <module>
    from .views import RegisterView
  File "/home/nappmyid/python/moneymanager/api/views.py", line 22, in <module>
    import requests as req_lib
ModuleNotFoundError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 58, in inner
    response = response_for_exception(request, exc)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 182, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 66, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 396, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 381, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 99, in get_caller
    resolver_match = resolve(request.path)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nappmyid/python/moneymanager/moneymanager/urls.py", line 24, in <module>
    path('api/',include('api.urls')),
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nappmyid/python/moneymanager/api/urls.py", line 5, in <module>
    from .views import RegisterView
  File "/home/nappmyid/python/moneymanager/api/views.py", line 22, in <module>
    import requests as req_lib
ModuleNotFoundError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 58, in inner
    response = response_for_exception(request, exc)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 182, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 66, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 396, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 381, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 99, in get_caller
    resolver_match = resolve(request.path)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nappmyid/python/moneymanager/moneymanager/urls.py", line 24, in <module>
    path('api/',include('api.urls')),
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nappmyid/python/moneymanager/api/urls.py", line 5, in <module>
    from .views import RegisterView
  File "/home/nappmyid/python/moneymanager/api/views.py", line 22, in <module>
    import requests as req_lib
ModuleNotFoundError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 58, in inner
    response = response_for_exception(request, exc)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 182, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 66, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 396, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 381, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 99, in get_caller
    resolver_match = resolve(request.path)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nappmyid/python/moneymanager/moneymanager/urls.py", line 24, in <module>
    path('api/',include('api.urls')),
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nappmyid/python/moneymanager/api/urls.py", line 5, in <module>
    from .views import RegisterView
  File "/home/nappmyid/python/moneymanager/api/views.py", line 22, in <module>
    import requests as req_lib
ModuleNotFoundError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 58, in inner
    response = response_for_exception(request, exc)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 182, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 66, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 396, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 381, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 99, in get_caller
    resolver_match = resolve(request.path)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nappmyid/python/moneymanager/moneymanager/urls.py", line 24, in <module>
    path('api/',include('api.urls')),
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nappmyid/python/moneymanager/api/urls.py", line 5, in <module>
    from .views import RegisterView
  File "/home/nappmyid/python/moneymanager/api/views.py", line 22, in <module>
    import requests as req_lib
ModuleNotFoundError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 131, in __call__
    response = self.get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 58, in inner
    response = response_for_exception(request, exc)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 182, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 66, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 396, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 381, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/debug.py", line 99, in get_caller
    resolver_match = resolve(request.path)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nappmyid/python/moneymanager/moneymanager/urls.py", line 24, in <module>
    path('api/',include('api.urls')),
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/opt/alt/python38/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nappmyid/python/moneymanager/api/urls.py", line 5, in <module>
    from .views import RegisterView
  File "/home/nappmyid/python/moneymanager/api/views.py", line 22, in <module>
    import requests as req_lib
ModuleNotFoundError: No module named 'requests'
Not Found: /moneymanager/static/rest_framework/css/bootstrap.min.css
Not Found: /moneymanager/static/rest_framework/js/csrf.js
Not Found: /moneymanager/static/rest_framework/js/bootstrap.min.js
Not Found: /moneymanager/static/rest_framework/js/prettify-min.js
Not Found: /moneymanager/static/rest_framework/js/default.js
Not Found: /moneymanager/static/rest_framework/css/prettify.css
Not Found: /moneymanager/static/rest_framework/css/default.css
Not Found: /moneymanager/static/rest_framework/js/jquery-3.5.1.min.js
Not Found: /moneymanager/static/rest_framework/js/ajax-form.js
Not Found: /moneymanager/static/rest_framework/css/bootstrap-tweaks.css
Unauthorized: /moneymanager/api/transfer/
Not Found: /moneymanager/static/rest_framework/css/bootstrap-tweaks.css
Not Found: /moneymanager/static/rest_framework/js/ajax-form.js
Not Found: /moneymanager/static/rest_framework/js/csrf.js
Not Found: /moneymanager/static/rest_framework/js/prettify-min.js
Not Found: /moneymanager/static/rest_framework/js/default.js
Not Found: /moneymanager/static/rest_framework/css/bootstrap.min.css
Not Found: /moneymanager/static/rest_framework/css/default.css
Not Found: /moneymanager/static/rest_framework/css/prettify.css
Not Found: /moneymanager/static/rest_framework/js/bootstrap.min.js
Not Found: /moneymanager/static/rest_framework/js/jquery-3.5.1.min.js
Bad Request: /moneymanager/api/login/social/google/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
{'t': 'ya29.a0AWY7CkkojkP0gEWT570a90DKHqyPuoLEN_a4PmfWkXo0MiaHeol2KaSnKcv_x5gu5SeINX283msv0RN6OYK8DU_QZoVFXq7Upu3xRM58PEuHHo9TU6p7hI_v4uGcOkdscCcyVnvs5WpeKAncwMdQoCZDCw3LrAaCgYKAWUSAQ4SFQG1tDrpXKI2tTdqnHy2kC24cxBWgA0165'}
Bad Request: /moneymanager/api/login/social/google/
Bad Request: /moneymanager/api/login/social/google/
Bad Request: /moneymanager/api/login/social/google/
Not Found: /moneymanager/media/profile/34e2e2ae-1b96-4c19-aa37-5a40ef7ac1f0.png
Not Found: /moneymanager/media/profile/34e2e2ae-1b96-4c19-aa37-5a40ef7ac1f0.png
Not Found: /moneymanager/media/profile/34e2e2ae-1b96-4c19-aa37-5a40ef7ac1f0.png
{'t': 'ya29.a0AWY7Ckmu3Qz7xLfGxHN2ePQB77KOd_QKwk558KGR-MCUT-BMo6lw_sVB0oAav_jMaqYi_d3iE3aD3KzHiZtMe7k0XuxmJ1FVK3T9k7BKi77r-a8Fok-nyhdNb_DzgBRwaRRROaPYTb1KN0AiJXusq_SP6gDACQaCgYKATcSAQ4SFQG1tDrpLIP7pVKMQEH0c155hd9pxg0165'}
{'user': {'first_name': 'Fernando', 'last_name': 'Nikolas R', 'email': 'fnikolas221@gmail.com'}, 'bio': 'Pencari Petualangan'}
{'photo': <InMemoryUploadedFile: 2e8cdcc3d033335c5f1d08b9a74ce5fff2a29ac2847f8531ebfa80702a5b9228.png (image/png)>}
Not Found: /moneymanager/media/profile/34e2e2ae-1b96-4c19-aa37-5a40ef7ac1f0.png
Not Found: /moneymanager/media/profile/34e2e2ae-1b96-4c19-aa37-5a40ef7ac1f0.png
Not Found: /moneymanager/media/34e2e2ae-1b96-4c19-aa37-5a40ef7ac1f0.png
Not Found: /moneymanager/media/34e2e2ae-1b96-4c19-aa37-5a40ef7ac1f0.png
Bad Request: /moneymanager/api/login/social/google/
{'photo': <InMemoryUploadedFile: 2e8cdcc3d033335c5f1d08b9a74ce5fff2a29ac2847f8531ebfa80702a5b9228.png (image/png)>}
Unauthorized: /moneymanager/api/rekening/
Bad Request: /moneymanager/api/login/social/google/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Bad Request: /moneymanager/api/login/social/google/
Bad Request: /moneymanager/api/login/social/google/
Bad Request: /moneymanager/api/login/profile/delete_photo/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Bad Request: /moneymanager/api/login/social/google/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Not Found: /moneymanager/moneymanager/media/profile/77299f68-70bb-433c-bf9b-efe81c862587.png
Not Found: /moneymanager/moneymanager/media/profile/77299f68-70bb-433c-bf9b-efe81c862587.png
Not Found: /moneymanager/moneymanager/media/profile/77299f68-70bb-433c-bf9b-efe81c862587.png
Not Found: /moneymanager/moneymanager/media/profile/77299f68-70bb-433c-bf9b-efe81c862587.png
Bad Request: /moneymanager/api/login/social/google/
Bad Request: /moneymanager/api/login/social/google/
Not Found: /moneymanager/moneymanager/media/profile/77299f68-70bb-433c-bf9b-efe81c862587.png
Bad Request: /moneymanager/api/login/profile/delete_photo/
Bad Request: /moneymanager/api/login/profile/delete_photo/
Bad Request: /moneymanager/api/login/profile/delete_photo/
Bad Request: /moneymanager/api/login/profile/delete_photo/
Bad Request: /moneymanager/api/login/profile/delete_photo/
Bad Request: /moneymanager/api/login/profile/delete_photo/
Bad Request: /moneymanager/api/login/profile/delete_photo/
Bad Request: /moneymanager/api/login/profile/delete_photo/
Not Found: /moneymanager/moneymanager/media/profile/77299f68-70bb-433c-bf9b-efe81c862587.png
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Not Found: /moneymanager/moneymanager/media/profile/77299f68-70bb-433c-bf9b-efe81c862587.png
Not Found: /moneymanager/moneymanager/media/profile/77299f68-70bb-433c-bf9b-efe81c862587.png
Not Found: /moneymanager/moneymanager/media/profile/77299f68-70bb-433c-bf9b-efe81c862587.png
Not Found: /moneymanager/moneymanager/media/profile/77299f68-70bb-433c-bf9b-efe81c862587.png
Not Found: /moneymanager/moneymanager/media/profile/77299f68-70bb-433c-bf9b-efe81c862587.png
Not Found: /moneymanager/moneymanager/media/profile/77299f68-70bb-433c-bf9b-efe81c862587.png
Not Found: /moneymanager/moneymanager/media/profile/77299f68-70bb-433c-bf9b-efe81c862587.png
Not Found: /moneymanager/moneymanager/media/profile/77299f68-70bb-433c-bf9b-efe81c862587.png
Not Found: /moneymanager/moneymanager/media/profile/77299f68-70bb-433c-bf9b-efe81c862587.png
Not Found: /moneymanager/moneymanager/media/profile/77299f68-70bb-433c-bf9b-efe81c862587.png
Bad Request: /moneymanager/api/login/profile/delete_photo/
Bad Request: /moneymanager/api/login/profile/delete_photo/
Bad Request: /moneymanager/api/login/profile/delete_photo/
Bad Request: /moneymanager/api/login/profile/delete_photo/
Bad Request: /moneymanager/api/login/profile/delete_photo/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
[UID:2035][2369306] Child process with pid: 2382242 was killed by signal: 15, core dump: 0
Bad Request: /moneymanager/api/login/social/google/
Unauthorized: /moneymanager/api/rekening/
[UID:2035][3143172] Child process with pid: 3143361 was killed by signal: 9, core dump: 0
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Bad Request: /moneymanager/api/transfer/9a32380f-7d9d-438d-aa45-51df080fdcde/
Bad Request: /moneymanager/api/transfer/9a32380f-7d9d-438d-aa45-51df080fdcde/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Bad Request: /moneymanager/api/login/social/google/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/391a8dac-e229-4695-801a-54a1fea61146/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Bad Request: /moneymanager/api/transfer/
Bad Request: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
[UID:2035][1853737] Child process with pid: 1896402 was killed by signal: 9, core dump: 0
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
OSError: LSAPI: Socket read/write error
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
[UID:2035][1250683] Child process with pid: 1251857 was killed by signal: 15, core dump: 0
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
OSError: LSAPI: File error
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
[UID:2035][120528] Child process with pid: 126746 was killed by signal: 15, core dump: 0
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Bad Request: /moneymanager/api/login/social/google/
Bad Request: /moneymanager/api/login/social/google/
Bad Request: /moneymanager/api/login/social/google/
Bad Request: /moneymanager/api/login/social/google/
Bad Request: /moneymanager/api/login/social/google/
Bad Request: /moneymanager/api/login/social/google/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
[UID:2035][1421078] Child process with pid: 1427739 was killed by signal: 15, core dump: 0
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
[UID:2035][1783778] Child process with pid: 1783979 was killed by signal: 15, core dump: 0
Unauthorized: /moneymanager/api/rekening/
[UID:2035][4107306] Child process with pid: 4107495 was killed by signal: 9, core dump: 0
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Bad Request: /moneymanager/api/register/
Bad Request: /moneymanager/api/register/
Bad Request: /moneymanager/api/register/
Bad Request: /moneymanager/api/register/
Bad Request: /moneymanager/api/register/
Bad Request: /moneymanager/api/register/
Bad Request: /moneymanager/api/register/
Bad Request: /moneymanager/api/register/
Bad Request: /moneymanager/api/register/
Bad Request: /moneymanager/api/register/
Bad Request: /moneymanager/api/login/social/google/
Internal Server Error: /moneymanager/api/register/
Traceback (most recent call last):
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/home/nappmyid/python/moneymanager/api/auth_serializer.py", line 48, in create
    with open(str(pathlib.Path(__file__).parent.resolve()) + '\\default_category.json') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/nappmyid/python/moneymanager/api\\default_category.json'
Bad Request: /moneymanager/api/register/
Bad Request: /moneymanager/api/register/
Bad Request: /moneymanager/api/register/
Internal Server Error: /moneymanager/api/register/
Traceback (most recent call last):
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/home/nappmyid/python/moneymanager/api/auth_serializer.py", line 48, in create
    with open(str(pathlib.Path(__file__).parent.resolve()) + '\\default_category.json') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/nappmyid/python/moneymanager/api\\default_category.json'
Internal Server Error: /moneymanager/api/register/
Traceback (most recent call last):
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/nappmyid/virtualenv/python/moneymanager/3.8/lib/python3.8/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/home/nappmyid/python/moneymanager/api/auth_serializer.py", line 48, in create
    with open(str(pathlib.Path(__file__).parent.resolve()) + '\\default_category.json') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/nappmyid/python/moneymanager/api\\default_category.json'
Bad Request: /moneymanager/api/register/
Bad Request: /moneymanager/api/register/
Unauthorized: /moneymanager/api/login/
Unauthorized: /moneymanager/api/login/
Not Found: /moneymanager/static/admin/css/base.css
Not Found: /moneymanager/static/admin/css/nav_sidebar.css
Not Found: /moneymanager/static/admin/js/nav_sidebar.js
Not Found: /moneymanager/static/admin/css/login.css
Not Found: /moneymanager/static/admin/css/responsive.css
Not Found: /moneymanager/static/admin/css/dark_mode.css
Not Found: /moneymanager/static/admin/css/base.css
Not Found: /moneymanager/static/admin/js/nav_sidebar.js
Not Found: /moneymanager/static/admin/css/responsive.css
Not Found: /moneymanager/static/admin/css/login.css
Not Found: /moneymanager/static/admin/css/dark_mode.css
Not Found: /moneymanager/static/admin/css/nav_sidebar.css
Makanan
Snack
Hiburan
Transportasi
Human Error
Shopping
Device & Internet
Tagihan
Ortu
Kebersihan
Obat & Vitamin
Hibah & Hadiah
Salary
Sembako
Edukasi
Pajak
Makanan
Snack
Hiburan
Transportasi
Human Error
Shopping
Device & Internet
Tagihan
Ortu
Kebersihan
Obat & Vitamin
Hibah & Hadiah
Salary
Sembako
Edukasi
Pajak
Unauthorized: /moneymanager/api/login/
{'t': 'ya29.a0AfB_byBX6_v8F0hs1FJLdLG56FAVVp2Xr0Mt-ImzhSd7fSAkbvcCboLXp46TAQmDhQSKqJwJJdSbE8NEKQwQqnb2c6jRaN-DizI1gGmlAvVyz3HciuLCYMUDygVLs-_4-c_GQScP8nBBv6zOUP5gedJ9oGyR0bt30AIfJgaCgYKAeASARISFQHsvYlskFvIapUJEEx6zkuZ06-Ahg0173'}
Bad Request: /moneymanager/api/login/social/google/
[UID:2035][590628] Child process with pid: 591496 was killed by signal: 9, core dump: 0
[UID:2035][590628] Child process with pid: 591574 was killed by signal: 9, core dump: 0
Bad Request: /moneymanager/api/login/social/google/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Bad Request: /moneymanager/api/login/social/google/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/login/refresh/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/rekening/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/transaksi/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/kategori/
Unauthorized: /moneymanager/api/utangpiutang/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/rekening/stats_summary/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/transfer/
Unauthorized: /moneymanager/api/login/profile/
Unauthorized: /moneymanager/api/rekening/
